#!/bin/env python3
import logging, sys
import helpers

if __name__ == '__main__':
    # Parse subcommand
    args = sys.argv[1:]
    if len(args) == 0:
        command_help(code=1)
    subcommand_name, args = args[0].replace("-", "_"), args[1:]
    subcommand = helpers.subcommand(subcommand_name)

    # Parse command-line flags
    options = {}
    positional = []
    while len(args) > 0:
        arg, *args = args
        if arg in ("-v", "--verbose"):
            options["verbose"] = True
        elif arg in ("-q", "--quiet"):
            options["verbose"] = False
        elif arg in ("-d", "--chroot"):
            options["root"], *args = args
        elif arg in ("-s", "--silent"):
            options["verbose"] = False
            options["silent"] = True
        else:
            positional.append(arg)

    logging.basicConfig(format="%(message)s")
    if options.get("verbose"):
        logging.getLogger().setLevel(logging.DEBUG)
    elif options.get("silent"):
        logging.getLogger().setLevel(logging.FATAL)
    else:
        logging.getLogger().setLevel(logging.INFO)

    # Run that command
    subcommand(*positional, **options)
    #import cProfile
    #cProfile.run("subcommand(*positional, **options)", 'restats')
